### ISSUE TITLE
interstitial ad, error code 602, "Fallback fullscreen ad failed"

### ISSUE THREAD

**Issue by phuct9** [fan-ADN/nendSDK-Android#6]
I ran the sample, nendSDK-Android-master , with
spotID : 802559
apiKey : e9527a2ac8d1f39a667dfe0f7c169513b090ad44
the interstitial ad successfully shown.

but when I use my own spotID and apiKey, 
on Android, I encountered error code 602 "Fallback fullscreen ad failed".
on IOS,  I encountered error code 204 "No delivery ads",
could there have been something wrong with my setting on www.nend.net?

**Comment by ghost** [comment]
Hi, @phuct9 

Maybe your requesting is denied by region restrictions . 
Please retry to request ad by Japanese region via VPN.

Then, if issue still unclear, we want to know more information about error.
Please modified our sample code & try again by your spotID & apiKey.

```java
-- mNendAdInterstitialVideo.addFallbackFullboard(485520, "a88c0bcaa2646c4ef8b2b656fd38d6785762f2ff");
++ //mNendAdInterstitialVideo.addFallbackFullboard(485520, "a88c0bcaa2646c4ef8b2b656fd38d6785762f2ff");
```

```kotlin
-- addFallbackFullboard(485520, "a88c0bcaa2646c4ef8b2b656fd38d6785762f2ff")
++ //addFallbackFullboard(485520, "a88c0bcaa2646c4ef8b2b656fd38d6785762f2ff")
```

Best regards

**Comment by phuct9** [comment]
Thank you for your assistance
I commented this line of code out:
//mNendAdInterstitialVideo.addFallbackFullboard(485520,"a88c0bcaa2646c4ef8b2b656fd38d6785762f2ff");
then I requested an ad from a japanese IP via VPN (ip: 66.133.76.9) but now, I get error 204 on Android and IOS instead.

error detail on Android: 
D/NEND_VIDEO: Click load interstitial button.
06-01 14:52:47.941 25945-25945/net.nend.sample.java I/nend_SDK: net.nend.android.NendAdInterstitialVideo.a:
                                                                You can use fallback option at Interstitial Ad. Let's check the wiki.
06-01 14:52:48.125 26256-26570/? I/AKMD2: AKMD_Release: Memory free.
06-01 14:52:48.658 25945-25945/net.nend.sample.java E/nend_SDK: net.nend.android.NendAdVideo$3.a:
                                                                Failed to load ad.
                                                                Status = 204: No fill ad.
                                                                    at net.nend.android.internal.c.e.c$a.a(VideoAdLoader.java:275)
                                                                    at net.nend.android.internal.utilities.a$f.call(NendAdExecutor.java:162)
                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                    at java.lang.Thread.run(Thread.java:818)
06-01 14:52:48.670 25945-25945/net.nend.sample.java W/NEND_VIDEO: onFailedToLoad interstitial
06-01 14:52:48.670 25945-25945/net.nend.sample.java W/NEND_VIDEO: VideoAdError code : 204

**Comment by ghost** [comment]
Thank you for your reply.

We confirmed to received your requesting from `66.133.76.9`. 
But some VPN service couldn't check to countries.
So, we found another VPN profile that be able connect `nend` :
* host : `gp-cm12-0821.lcv.ne.jp`
* IP : `124.246.135.53`

http://www.vpngate.net/en/

Please use this VPN profile & retry again.

Best regards
