### ISSUE TITLE
Binary XML file line #80: Error inflating class net.nend.android.NendAdView

### ISSUE THREAD

**Issue by jackyhieu1211-hn** [fan-ADN/nendSDK-Android#9]
Hello admin. I have a problem. 

      Binary XML file line #80: Error inflating class net.nend.android.NendAdView

this is error on device: HMD Global Nokia 7 Plus Android 9. API 28.
Please check and fix

**Comment by ghost** [comment]
Hi, @jackyhieu 

Thank you for reporting.
Could you take more information below:

* Which version of nendSDK do you use in your application
* Is this problem occur only HMD Global Nokia 7 Plus?
  * We cannot find on Pixel 3 XL, API 28
* Please show us full adb log if you could.
* Please show us your codes where are using nendSDK on your app if you could.

**Comment by pacojp** [comment]
nendSDK

* 5.0.3 => NG
* 4.0.5 => OK

Nexus 5(android4.4)

**Comment by fan-t-fukuoka** [comment]
Hello @pacojp 
Thank you for comment.
Could you take more information below:
- Please show us full adb log if you could.
- Please show us your codes where are using nendSDK on your app if you could.
  - I want to know how to implement `NendAdView`.

**Comment by pacojp** [comment]
@fan-s-fujikawa 
I am Sorry. It was my fault.

I did not read this page.

https://github.com/fan-ADN/nendSDK-Android/wiki/About-namespace-of-Attribute

**Comment by jackyhieu1211-hn** [comment]
Sorry for the late reply
Version Nend SDK : 5.0.3
Is this problem occur only HMD Global Nokia 7 Plus? Yes. Only  HMD Global Nokia 7 Plus

This is logcat

     2019-01-03 15:20:05.056 19449-19449/packagename:unityplayer E/AndroidRuntime: FATAL 
     EXCEPTION: main
    Process: packagename:unityplayer, PID: 19449
    java.lang.RuntimeException: Unable to start activity ComponentInfo{packagename/com.example.presentation.activity.space.SpaceActivity}: android.view.InflateException: Binary XML file line #76: Binary XML file line #76: Error inflating class net.nend.android.NendAdView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2928)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3063)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6729)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.view.InflateException: Binary XML file line #76: Binary XML file line #76: Error inflating class net.nend.android.NendAdView
     Caused by: android.view.InflateException: Binary XML file line #76: Error inflating class net.nend.android.NendAdView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
        at com.example.presentation.activity.unity.UnityPlayerActivity.onCreate(UnityPlayerActivity.kt:100)
        at com.example.presentation.activity.space.SpaceActivity.onCreate(SpaceActivity.kt:171)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3063)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6729)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

This is xml

           <RelativeLayout xmlns:ads="http://schemas.android.com/apk/res-auto"
            xmlns:nendsdk="http://schemas.android.com/apk/res-auto"
            android:id="@+id/adViewLayout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_alignParentBottom="true">

            <android.support.v7.widget.AppCompatImageView
                android:id="@+id/btnJoinRoom"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_centerHorizontal="true"
                app:srcCompat="@drawable/peeping_entering_the_room" />

            <net.nend.android.NendAdView
                nendsdk:NendApiKey="c5cb8bc474345961c6e7a9778c947957ed8e1e4f"
                nendsdk:NendSpotId="3174"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"/>

        </RelativeLayout>

**Comment by ghost** [comment]
Hi @jackyhieu 

Thank you for reply and information.

1. Your XML layout doesn't seems to have `xmlns:android`.
Please add `xmlns:android`. 

1. `NendAdView`'s width is not dynamic by parent width.
We recommend change to `wrap_content` for `NendAdView` width.

1. Please check that issue is occurs or not also on [our sample app](https://github.com/fan-ADN/nendSDK-Android)  if this issue still occurs after changed above recommends.

1. Your adb log print your package name `unityplayer`.
Please let us know which version of Unity do you use if you use Unity?

**Comment by jackyhieu1211-hn** [comment]
Hi admin
1. OK
2. OK

**** Result : Get error same *****
3. OK
**** Result 👍  App worked *****
4. Unity latest version : 2018.3.0f2
-  I tried create a new project. And I worked. 
- My app has integration android and unity. I think that's the problem. But it only crash on HMD Global Nokia 7 Plus Android 9. API 28.
- I only have 1 android 9 device so I can't check it on another device
- I temporarily fix the error by disabling nendsdk on android 9.

**Comment by ghost** [comment]
@jackyhieu 

> 3. OK
**** Result 👍 App worked *****

Good! 
We think this issue may occurs by your unity project, not device.
> 4. Unity latest version : 2018.3.0f2

Please check [our Unity example](https://github.com/fan-ADN/nendSDK-Unity) if your project calls API of nendSDK from Unity's layer.

Could you share us the unity project that occurs this problem?
We'll check the build project and codes that implementation nendSDK if you share unity project.
**The Unity project is not means equals your production codes.**
It's enough includes codes that occurs this problem other environment.

**Comment by AbdubositKhasanov** [comment]
`mmmmmmmmmmmmmm
mmmmmmmmmmmm
mmmmmmmmmmmm
mmmmmmmmmmm`

**Comment by AbdubositKhasanov** [comment]
mmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmm
mmmmmmmmmmmm
mmmmmmmmmm
mmmmmmmmmm
m
